version: '3'

services:
  front:
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - back
  back:
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./back/model.pkl:/app/model.pkl