# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEndtoend():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_endtoend(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(1936, 1048)
    self.driver.find_element(By.ID, "title").click()
    self.driver.find_element(By.ID, "title").send_keys("SNK")
    dropdown = self.driver.find_element(By.ID, "genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Action']").click()
    dropdown = self.driver.find_element(By.ID, "genre")
    dropdown.find_element(By.XPATH, "//option[. = 'Adventure']").click()
    self.driver.find_element(By.ID, "description").click()
    self.driver.find_element(By.ID, "description").send_keys("blablabla")
    self.driver.find_element(By.ID, "type").click()
    dropdown = self.driver.find_element(By.ID, "type")
    dropdown.find_element(By.XPATH, "//option[. = 'OVA']").click()
    dropdown = self.driver.find_element(By.ID, "producer")
    dropdown.find_element(By.XPATH, "//option[. = '12DiaryHolders']").click()
    dropdown = self.driver.find_element(By.ID, "anime-studio")
    dropdown.find_element(By.XPATH, "//option[. = '10Gauge']").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.CSS_SELECTOR, "p").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
